### PR TITLE
Use gesture recognizers instead of touches(Began|Ended|Cancelled)

### PR DESCRIPTION
**Pull request by mattjgalloway**
Touch handling via touches(Began|Ended|Cancelled) is pretty old school. It also means that if you put an OHAttributedLabel inside a view that has a touch gesture recogniser on it then it won't fire on links being tapped as gesture recognisers use an inverted responder chain. These commits fix all that by converting OHAttributedLabel to use a gesture recogniser.

### CODE REVIEW

**Comment by mRs-** [comment]
I got a bunch of Cycle & Roots with this. The gesture recognizers hold the objects open and are wasting memory in my apps. I just downgraded to 3.4.3 and all seems fine.

**Comment by mattjgalloway** [comment]
@mRs- I don't particularly see why you're getting leaks with this. I don't see any myself and it's just a standard gesture recogniser on the view. Can you shed any more light on where the leak is happening? Maybe send over an instruments trace?

**Comment by mRs-** [comment]
Here a screenshot of instruments
screen shot 2013-10-10 at 17 02 55

I am creating the UINib instance in the heightForRowAtIndexPath tableView delegate call, because of my complex application. 

In my cell class i am calculating the height for the cell:

``` objc

CGSize constraint = CGSizeMake(300, MAXFLOAT);
CGSize size = [self.richTextLabel.attributedText sizeConstrainedToSize:constraint];
CGFloat height = size.height;

return height + (CELL_CONTENT_MARGIN * 2);
```

This works in 3.4.3 without any problem under 3.5 there is the gesture recognizer cycle of death :/

**Comment by mattjgalloway** [comment]
@mRs- Oh I see the issue. My pull request was not merged properly by @AliSoftware. Notice in `dealloc` it is not releasing `_gestureRecogniser` (for the case you're not using ARC). I'll send another PR, but in the meantime you can just add this into dealloc:

```
[_gestureRecogniser release]; _gestureRecogniser = nil;
```

**Comment by mattjgalloway** [comment]
@mRs- see #161 if you want the fix right away before it's merged.

**Comment by mRs-** [comment]
But i am using ARC

**Comment by mattjgalloway** [comment]
@mRs- How are you building OHAttributedLabel though. Maybe that project of yours is set to non-ARC? Anyway - please feel free to investigate further. Or if you can provide a sample project showing the problem then I can take a further look. I don't see this in my own app which makes extensive use of OHAttributedLabel with gesture recognisers.

**Comment by AliSoftware** [comment]
How do you integrate `OHAttributedLabel` to your project?
CocoaPods? Separate project in your workspace? Static library compiled separately?

And which settings are you using to compile it?
I don't see this in my own app either.

**Comment by mRs-** [comment]
I build an example project with the problem.

**Comment by mRs-** [comment]
Have Fun :)

https://github.com/mRs-/OHAttributedLabelBug

**Comment by AliSoftware** [comment]
Strange facts:
- If for the sake of testing I replace `_gestureRecogniser = [[OHTouchesGestureRecognizer alloc] initWithTarget:self action:@selector(_gestureRecognised:)];` with `_gestureRecogniser = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(_gestureRecognised:)];` the leak is still here :arrow_right: it does not seem to be related to the `OHTouchesGestureRecognizer` class itself
- If I don't set the delegate nor add the `_gestureRecognizer` to the `view`, just create it :arrow_right: I still got the leak, so this is not related to the fact the GR is added to the view, nor that there would have been some cycle because of self retaining the GR and being the delegate alltogether neither.
- If I simply alloc/init the `UITapGR` in `commonInit` and right the line after I set it to `nil`, still without adding it to the view :arrow_right: I still have the leak! Whereas I just create an object then immediately reset it to nil!!
- If I log the number of times `commonInit` gets called (adding a breakpoint with the action "Log Command" "%H") and the number of times `dealloc` gets called, as soon as I set `self.tableView = nil` (to release the `OHAttributedLabels` that were displayed on screen and retained by the `tableView`) they are balanced completely (11 calls to `commonInit`, 11 calls to `dealloc`)

I'm starting to wonder if it is not a side-effect of the `UITableView` keeping a reference to a cell (thus an `OHAttributedLabel`, thus a GR) or a false positive or whatnot?!

```
- (void)commonInit
{
    ...
    _gestureRecogniser = [[OHTouchesGestureRecognizer alloc] initWithTarget:self action:@selector(_gestureRecognised:)];
    _gestureRecogniser = nil; // still leaks even after this line!!!
//    _gestureRecogniser.delegate = self;
//    [self addGestureRecognizer:_gestureRecogniser];
}
```

**Comment by mattjgalloway** [comment]
@mRs- @AliSoftware If you add the line I said earlier, in `dealloc`, and as per the other PR I've already sent and been merged, then it doesn't leak any more. It is not using ARC in this setup. After I've setup CocoaPods stuff, the target that builds OHAttributedLabel does not have ARC enabled.

So:
@mRs- - either add the line I stated earlier, or update to HEAD of master.
@AliSoftware - maybe you should do another pod release?

**Comment by mRs-** [comment]
I didn't now, that OHAttributed label is not using ARC at all. The leak is gone if i use the patch of your commit so it's fine now. 

Maybe we should really switch to ARC like you mention it in https://github.com/AliSoftware/OHAttributedLabel/pull/163

**Comment by mRs-** [comment]
@AliSoftware a new release for CocoaPods would be great, i think 3.5.1 is right on the way with this fix :)

**Comment by AliSoftware** [comment]
Agreed for dropping non-ARC code and forcing ARC use. But I think if we do that we should do it all the way, even removing all the LOC embedded inside `#if ! __has_feature(objc_arc) ... #endif` blocs, to make the code even cleaner, and be coherent with the requirements announced in the podspec, right?

**Comment by AliSoftware** [comment]
#163 merged and now using ARC when using CocoaPods.
LMK if this solved this issue too so we can definitively consider it closed :+1:

**Pull request closed without merging**
