### PR TITLE
Fixed a crash caused by dealloc not resetting textFrame to NULL after rel

### PR DESCRIPTION
**Pull request by ericflo**
Fixed a crash caused by dealloc not resetting textFrame to NULL after releasing the reference (a subsequent call to resetTextFrame would pass the if conditional and crash on trying to release the memory.)

### CODE REVIEW

**Comment by AliSoftware** [comment]
Hi @ericflo

Thanks for the fix. Anyway, how come any method can be called after `dealloc` ?
The dealloc method is called only when the instance is deallocated from memory, so the instance of the object doesn't exit anymore after this method and no method will be called on this instance afterwards (because there is no such instance anymore!)

So the crash you're describing can't really happen actually. (If it did happen, that reflects a memory leak/dandling pointer anywhere else in your code that makes your code call random methods on zombie/deallocated objects)

I will merge your fix anyway as it won't hurt but don't forget to check your code using Instruments to check for external leaks too.

**Comment by ericflo** [comment]
Wow, that's a good point--I fell into the trap of fixing the symptoms and not the cause. Thanks for the update and sorry for the noise :)

**Comment by AliSoftware** [comment]
No pb you're welcome… happy coding ;-)

**Comment by AliSoftware** [comment]
Actually, as pointed out by @AshFurrow in issue #29, it seems that the problem was actually generated by a call to drawInRect **after** dealloc (probably done in the `dealloc` implementation of Apple's UILabel)… which is new to iOS5.

Did you get the crash while you were testing my class under iOS5? If so, this ma explain why you got the crash, and resetting the frame to NULL do solve the problem, as Apple now seems to call drawInRect in its own UILabel's dealloc method.

**Comment by ashfurrow** [comment]
Yes, I experienced the issue when testing on iOS 5. It does seems bizarre that drawRect would be called after [super dealloc] is called.

**Comment by AliSoftware** [comment]
Yeah it seems bizarre to me too. Maybe it is setNeedsDisplay that makes it crash instead of drawRect (as it tries to CGRelease the textFrame a second time), but anyway I don't understand why setNeedsDisplay is called.

Maybe it is a side-effect, e.g. they may have a property `xxx` for which they set an observer, so that when it's changed, it calls `setNeedsDisplay` automagically — this makes sense to me, as this may be a tiypical use of KVO.
But if then in UILabel's `dealloc` method they use `self.xxx = nil` and not `[xxx release]`, this will trigger the `willChangeValueForKey:` and the KVO mechanism, which will call setNeedsDisplay…?

That's just a theory, but this may explain why this would happen and why `setNeedsDisplay` is called even if it would not be logical to call it explicitely in dealloc.

I will do more in-depth tests when I will have time to try iOS5 (very busy right now). Thanks for the followup anyway

**Pull request merged**
