### PR TITLE
Added linkColor (UIColor) and underlineLinks (BOOL) properties

### PR DESCRIPTION
**Pull request by triplef**
Two more properties to allow users to customize how the links are displayed. linkColor can be nil to disable automatic link coloring, which together with underlineLinks=NO completely disables automatic link formatting.

Thanks for your recent work, the new touch detection works much better now!

Frederik

### CODE REVIEW

**Comment by AliSoftware** [comment]
Thanks
Your code introduce a leak as you forgot to release the linkColor, but I will fix this in a next commit after merging your addition

**Comment by triplef** [comment]
Cool, thanks. I release linkColor in dealloc, not sure where else it should be released.

**Comment by AliSoftware** [comment]
That's it. Actually your code is OK, my bad. I didn't saw the diff in dealloc.
Actually GitHub acts strange on this pull request, when I checked for the diff I only saw the first lines of the diff. Now that I retry it's ok...
But github also tells me it cannot merge automatically this commit (but I don't understand what could conflict) so I'll need to merge manually

**Comment by triplef** [comment]
I think it might be because there are two more commits before this one in my timeline which I didn’t include:
https://github.com/triplef/OHAttributedLabel/commit/2009f065843519b98fddf6571a0109b9b7fddf92
https://github.com/triplef/OHAttributedLabel/commit/03647e18e41e693c8c57522ed4fc35898c735503

**Comment by AliSoftware** [comment]
Yep that certainly was the reason.
(Kind of a mess to use git from commandline to merge branches that are not synchronous !)

I finally managed to do the merge, closing this pull request.

**Comment by AliSoftware** [comment]
FYI, new commit/pull that allows you to manage the underlining and colors in a more finest way :
- You can use different underlining styles (dashes, dots, …) and not only plain underline
- In the delegate, in addition to manage color on a per-link basis, you can also manage the underlining this way too
  See my sample project for a way to render visited links in a different color+underline using this new features

In addition, I did some cleaning in the header file to make it easier to read (as it is the only "documentation" for now, it should be as readable as possible) :
- I grouped properties together
- I also removed instance variables that were associated with @properties (as this class is only for iPhone and iPhone uses the Modern Runtime which synthesize ivars for @properties automatically if not present)

**Note**: You should merge with this asap : as I changed the order of the lines in the header file, this will not make the merge easy if I do other modifications later.

**Comment by triplef** [comment]
Thanks, good stuff.

Is there a good way to get our branches synchronous again? I guess you have to pull the two missing commits (links above). One of the commits is already part of one of yours (changing touchesBegan: to touchesEnded:), the other one might make sense for you too (support for text shadow).

Thanks again for your great work!

**Comment by AliSoftware** [comment]
It seems our branches are already synchronous (My last merge took into account your text shadow fix)
see : https://github.com/AliSoftware/OHAttributedLabel/network

**Pull request closed without merging**
