### PR TITLE
Add LineHeight Adjustment Methods

### PR DESCRIPTION
**Pull request by iAladdin**
Add LineHeight

But How to let Label2 to fit this change ?

And How to compute the size of NSAttributedString?

### CODE REVIEW

**Comment by AliSoftware** [comment]
Thanks, I will try to review your code this weekend.

What do you mean by "How to let Label2 to fit this change" ?

To compute the size of an NSAttributedString, use the methods I provide in the NSAttributedString+Attributes category.

**Comment by iAladdin** [comment]
I have use it, But it's not correct.Maybe I use it with a wrong way, please check it.! I use it in the demo, sizeTofit

**Comment by AliSoftware** [comment]
Sorry didn't have time this weekend to check it out, will come back to this only next week

**Comment by SlavaBushtruk** [comment]
Is any progress on this? I'm really interested in LineHeight property.

**Comment by travisjeffery** [comment]
Ditto @SlavaBushtruk

**Comment by iAladdin** [comment]
@SlavaBushtruk @travisjeffery 
You could have try with the commit in this pull-request.
Let me know the result,ok?

**Comment by nfbelmont** [comment]
Hi iAladdin, first of all, this is a ver necessarily function and i appreciate to you to do this. And Thanks. I just only one thing to said. I was trying to create a simple rich textview with this code, but with some certainly kind of fonts, the line height was different. I tried this and help me a lot to understand the line height using  CTParagraphStyleSetting. 
But i change kCTParagraphStyleSpecifierLineSpacing  for kCTParagraphStyleSpecifierMaximumLineHeight. It was more customized. This help me to specified more the line height of this control.

**Pull request closed without merging**
