### PR TITLE
Fixes for link tracking

### PR DESCRIPTION
**Pull request by triplef**
Two small fixes for link tracking. Feel free to pull.

Thanks!

Frederik

### CODE REVIEW

**Comment by AliSoftware** [comment]
Thanks for this fix and for your interest in OHAttributedLabel :)
I will check your code and pull it as soon as I'm back home.

Your pull  request made me realize I think I forgot to push my last modifications to github, and some of them are about links too (especially tap detections which is now more efficient), so you may be interested too. I'll let you know

**Comment by stigi** [comment]
Can I jump in on this :)
- I would expect the custom links to also appear when automaticallyDetectLinks is NO. They are manually added links and should override automaticallyDetectLinks.
- Also I would perform the link handling in -touchesEnded with the -pointInside method always returning YES and the -touchesEnded should check if a link was hit (also only if the link was initially hit in -touchesBegan).

Checking for hitting a link in -pointInside is bad, since this affects the responder chain. The label should stay the responder for all the touches that are hitting it. If you intend to increase the sensitive area of the touch (kDeltaY in -linkAtPoint:) it would be a better solution to do this in a -hitTest method.

I'm going to implement all of this now for our fork since we're going to need it like that. If you like I can let you know when I'm done via a pull request :)

Best,
Ullrich

**Comment by triplef** [comment]
Ullrich: good stuff! Looking forward to your fork. :)

Frederik

**Comment by AliSoftware** [comment]
@stigi : Thansk for the feedback.
Can you wait until tomorrow before adding this ? As I said earlier, I realized that there are some modifications I made that I forgot to push on github, and some of them are regarding what you are talking about, especially a better sensitive area on touch. You may still want to adapt my code to your needs then, but I guess my fixes (that are already available) will reduce your work, and will ease the merge between the two forks.

## 

The reason I added the implementation in pointInside is because I use my OHAttributedLabel sometimes in an UITableViewCell. Keeping the whole label tappable makes the cell not-tappable, as when tapping on a label that does not contain links (or e.g. a label with a lot of text but only a small link in that big text), the label being in the responder chain will catch the touch event (even if we didn't touch the link in the label)... and then the UITableViewCell itself will never receive the touch event even if the user expects it to.

Implementing pointInside allows me to catch the touch events only if we touch a link in the label, and pass the touch event to the next responder, typically the UITableViewCell the label is into, if there was no link under the touch.

**Comment by AliSoftware** [comment]
I just merged your pull requests right now.
I also did the push I told you about, the one I did forgot to do, which improved link detection.

I also just added the two @stigi 's suggestions :
- now automaticallyDetectLinks does not affect custom links anymore
- a new boolean @property called "onlyCatchTouchesOnLinks" (defaulting to NO) allows to switch between the two behaviors of pointInside.
- With "onlyCatchTouchesOnLinks=YES", touches will only be caught by the OHAttributedLabel if there is a link under the CGPoint, and pass thru to the next responder if not, as I expect in my apps.
- With "onlyCatchTouchesOnLinks=NO", pointInside will always return YES (in fact will call the super's method) and touches will always be caught by the OHAttributedLabel, as YOU expect

This way both behaviors (the one you expect with the label always catching touches, and the one I need that pass the touch to the UITableViewCell under it when the touch is not on a link) are possible, depending on your needs :)

Note: I didn't test every use-cases for these modifications yet ; everything seems OK but if you see any side effects, let me know

**Comment by stigi** [comment]
Thanks for merging all that stuff :)
Having the onlyCatchTouchesOnLinks property makes sense and is fine.
I'll clean up the touch code a bit (-pointInsicde vs. -hitTest) and will try to add highlighting to links that are currently touched. Will also test some more edge cases.
Never used CoreText. Do you know of an easy way to get the typographical bounds of the link so I can use them to draw the highlight? If not I'm sure I'll find one :)

**Comment by triplef** [comment]
@stigi: Link highlighting would be fantastic. CTRunGetTypographicBounds() should be what you are looking for. Looks like like you will have to get the CTLine objects from the frame, then get the line’s glyph runs corresponding to the links. Hope that helps.

**Comment by AliSoftware** [comment]
@stigi can you explain a bit what you intend to do about the "touch code" ? I read on the net that making some zones "transparent for the touches" should be done in `pointInside` and not in `hitTest`, which makes sense to me as `pointInside` simply returns `YES` or `NO` whereas `hitTest` does much more, as it has to manage reccursive calls on its subviews and so on. I read the Apple documentation on hit testing but seems to have some contradictory information on this, the doc is not very clear on which method should be used.
Every example I saw for exemple on circle-shaped buttons overloaded `pointInside` and not `hitTest`, and works just fine (and in fact the implementation is easier). What benefits whould be to use `hitTest` (and having to manage calls on subviews) instead?

About the **links highlighting**, that's a very good idea. Be careful anyway, I guess it won't be as tricky as it seems: as pointed by @triplef, you can use `CTRunGetTypographicBounds()` but will need to loop on every CTLine, especially to manage links that runs across multiple lines. You will also need a `CGGraphicContext` to pass to `CTRunGetTypographicBounds()`, which you don't have in touchesBegan but only in drawRect. Of course you will need to draw the rectangle by yourself as NSAttributedStrings don't have an attribute for changing the background color of a run of text.
Looking forward to this addition about text highlighting anyway :) Thx

**Comment by stigi** [comment]
with all touch code it's always important to keep userEnabled state, invisibility etc. in mind. My proposed implementation would look like this: https://gist.github.com/966250 (without `-pointInside` being implemented at all).

i'm implementing link highlighting at the moment. it'll take a bit since i'm reading the core text documentation while i'm at it (must say i already like it :)). basically what i'm going to do is, remembering the active link in `-touchesBegan` and forgetting it in `-touchesEnded` and `-touchesCanceled`. all of those methods trigger `-setNeedsDisplay`. in `-drawRect` i'll then draw a highlight under the active link. something like that :)

**Comment by AliSoftware** [comment]
Ok but as I understood the Apple documentation, `pointInside:withEvent:` is only called by `hitTest:withEvent:` and only if `userInteractionEnabled` is YES and `alpha > 0.01`, so implementing `pointInside:withEvent:` should take this properties into account too, right?
I have to admit that I never found this hit-testing documentation very clear. That's not the first time I wonder about which of  `pointInside` or `hitTest` we have to overload. My researches on google told me pointInside was fine and easier then recommanded, but I may be wrong.

---

_**Note:**_ In your gist code above, I recommend that you only check if `linkAtPoint:` is `nil` if `onlyCatchTouchesOnLinks` is set. This way, if `onlyCatchTouchesOnLinks` is set to NO (which is the default), it will be optimized as you won't need to execute this code and it would avoid looping thru all CTLines to find a match. You better avoid this useless loop especially if you have a long text with a big number of lines ;-)

You may simply write this instead, as the second part of the `&&` operator is only evaluated if the first part is true, and ignored if it is false: `if (self.onlyCatchTouchesOnLinks && ([self linkAtPoint:point] == nil))`

**Comment by stigi** [comment]
we had a discussion in the office and came up with what we think is the right solution: https://gist.github.com/966295 (without the optimization you suggested)

if the label contains a subview that should handle the event than we shouldn't even check for the link being touched.
we can't do this in `-pointInside` but only in `-hitTest`

**Comment by AliSoftware** [comment]
You're right. Seems fine for me!

**Pull request merged**
