### PR TITLE
Change label's text color when highlighted.

### PR DESCRIPTION
**Pull request by hollance**
I used the OHAttributedLabel as a subview of a UITableViewCell. When the table cell is tapped, regular labels switch their text color to the highlighted color. OHAttributedLabel did not do this, so I added it in. Seems to work just fine. :-)

### CODE REVIEW

**Comment by AliSoftware** [comment]
Hi hollance and thanks for the change and for letting me know about it ! I'll probably merge this soon !

Anyway, I see a problem with your code : what if the user customized some colors of the NSAttributedString ?
e.g. if we use an NSAttributedString with some words in black, others in blue, others in red...
When the OHAttributedLabel is highlighted, the whole text will use the same highlightedColor even if the original text had multiple colors (which is also the case if you have URLs/links in your text that gets automatically detected and displayed in blue)
But in the other hand, it is also useful for you case when you don't have links in your OHAttributedLabel and only one text color, therefore your correction...

I think we have to offer both possibilities. I wonder what the behavior will be if highlightedTextColor is set to nil, I think in this particular case we expect the highlightedColor to have no effect, not changing the text color (and keeping the original colors of the text even if there are multiple colors), but is this the case, have you tested this ? (I am not on my mac right now so I can't check) A simple fix would be to add a "&& self.highlightedTextColor" in the condition you added.

Thanks anyway, keep me posted

**Comment by hollance** [comment]
I don't think it's a problem to set the entire view to the highlighted color. If the label is used on a UITableViewCell and that cell is selected, its background typically becomes a dark blue gradient. This is a temporary state. It looks good when the entire text switches to a light color (default is white) to contrast with the blue gradient.

However, your suggestion to check for self.highlightedTextColor != nil is a good suggestion. I just tested with a regular UILabel and that keeps its original color when it is highlighted but its highlightedTextColor is set to nil. My change to OHAttributedLabel crashes when you do that, so it definitely needs that extra check. With that in place users can decide to keep the original colors upon highlight. I'll update my fork.

**Comment by AliSoftware** [comment]
yes I see what you mean, but I personally sometimes uses custom background and selectedBackgroundViews for my custom UITableViewCells too, and I think the users of my class should be able to choose to use the highlightColor or not depending on the colors he uses in his UI, even if the state is temporary ;-)
So I agree it is better to use the highlightedColor that not to use it, but if we can let the user choose that's even better :-P

Anyway, your test and conclusion is great : it means the nil value for highlightedTextColors answers everything.
I will surely do the marge with your commot during the week when you have added the extra nil check.
(I should add some security-checks in "NSAttributedString+Attributes" methods anyway for cases when the parameter is nil to avoid potential crashes)

Thanks again

**Comment by AliSoftware** [comment]
pull/patch done !

FYI, I also just added a new modification to my source code, that underline the links (previously autodetected-links and custom links in the OHAttributedLabel were displayed in blue, but not underlined). My NSAttributedString category also adds setTextIsUnderlined:range: method too.

**Pull request closed without merging**
