### PR TITLE
Highlighting of touched link

### PR DESCRIPTION
**Pull request by stigi**
Please have a look at the code in drawRect.
I tried to write it as clear as possible :)

Hope reading it doesn't require aspirins :D

### CODE REVIEW

**Comment by AliSoftware** [comment]
Thanks for this modifications. Some remarks you should check anyway (before I can do a working merge):

`CGFloat height = ascent + descent;`
Not sure about this. I would have said `ascent - descent` as, to my experience I think I remember the descent being **negative**. Did you try a breakpoint in the code to check that value?

`floorf(CGRectGetMinY(linkRunRect)) - 3,  // TODO: find out where this offset comes from`
About this magic number : did you empirically determine it? If so, is it quite constant **whatever the size of the text is**? Or is it dependant on the UIFont and the font size? Isn't it relative to the font descent? (And maybe related to the previous comment about the descent being negative?)

**Comment by AliSoftware** [comment]
Still about the flooring & ceiling of the CGRect, won't it be clearer to **use the CGRectIntegral function** instead?

Why do you need to hit pixels anyway, to avoid antialiasing on the rectangle when drawing at a subpixel level? Maybe **disabling the antialiasing in the CGContext** whould be clearer instead then?

**Comment by AliSoftware** [comment]
Last question : I see you **loop thru the CTRuns of a given CTLine** when you determine that the link is in (or across) that CTLine. I guess that's for the cases of links that are across CTRuns in a given line, especially if the text composing the link uses different font sizes and styles and so on, so that to consider their different typo bounds? (or maybe there is another reason I didn't realize?)

I that's exactly for this use case, wouldn't it be prettier to **draw a single rectangle** that encapsulates the typo bounds of the whole link, instead of breaking up the rectangle in multiple parts? (The typo bounds I am talking about would of course match the union of the CGRects you compute for each individual CTRun)
This way we would only have a big rectangle that is as high as the highest CTRun in the link, and **avoid some "stairs effect"** when dealing with a link that is both in 12px for one part and 24px for another.

Any suggestion about that?

**Comment by AliSoftware** [comment]
Have to say I am a bit frightened by this last code in drawRect. Not that requires aspirin :P It is pretty clear and understandable. But I noticed in my application that **using CoreText is a bit slow**. Computing bounds of a text drawn using CoreText are some of **the most expensive calls** in my app (when profiling it using **Instruments**).

For example, in my app I have a UITableView and in each cell there is a OHAttributedLabel with variable text (thus variable cell heights). If I use CoreText to compute the height of the text for each cell in `tableView:heightForRowAtIndexPath:`, this **slows down the first scroll** of my TableView **in a significant way** (of course then the value is cached by UITableView so the scroll is efficient and fluid). If I uses UIKit instead, the reactivity of this first scroll is much more efficient (but I then got rounding problems as UIKit does not return the same values as CoreText and I ended up sometimes missing a line, sometime having a spare line for nothing)

I wonder what would be the effects of complexifying the `-drawRect` method in these conditions?
On the other hand, you additions only have to do some more work in activeLink is not nil (so only if the tableview is still / not scrolling and we are in a touch gesture), but as I already had performance issues with CoreText and reactivity problems, and as it is inacceptable to have my tableview displaying the list of comments slows down like this, I will need to instrument it again.

**Comment by stigi** [comment]
quite some feedback :)
let me go trough it one by one:
- decent: Yes, did check. On a font with point size of 12 ascent + descent equals to 12. So **descent is positive**. Not sure about the leading though.
- I didn't check if the 3 will change depending on the ascnet/ descent/ pointsize. Will do so next.
- CGRectIntegral: didn't know about that one.. :) It makes perfect sense to **use CGRectIntegral**! I've never disabled aliasing in CGContext, will try that solution as well.
- Looping through CTRuns: I do that since I can't get the bounds of a range of characters from CTLine (correct me if I'm wrong). Creating a single rect that is a **union of the bounds of successive CTRuns** makes sense.
- drawRect performance: We haven't used the label in TableCells yet. But we're planning to do so (that's actually why I jumped on the wagon to improve it :)). We're also very particular when it comes to scrolling speed of tables. From a theoretical perspective I don't see any implications in the code I added to `-drawRect`. What we should care about is not calling `-setNeedsDisplay` to often. Scrolling the table will not result in the lable being redrawn. That's what I like on the approach of using CoreText to draw the text once and for all :)

There are some thing's I noticed while working on the code.
In each call of `-drawRect` a new instance of textFrame is created. Is this necessary?
Also in `-drawRect` the rect in which the text is rendered according to `self.centerVertically` & `self.extendBottomToFit`. We don't do this when detecting touches on links. I didn't try out if this has implications but I assume we'll have to remember the rect together with the textFrame..

**Comment by stigi** [comment]
Ok, here are my findings:
- the 3pt offset was actually the descent which i didn't substract from the origins of the typographical rect. That mystery is solved.
- `CGContextSaveGState` claims to store the anti aliasing state but it actually doesn't do that. That's why I sticked with `CGRectIntegral`

**Comment by stigi** [comment]
I also created two helper methods to extract the code that checks if a character range is inside a CTLine/ CTRun. That cleans up the code in `-drawRect`.
I also add `inline` to the helper methods. That should speed them up a (tiny) bit.

**Comment by AliSoftware** [comment]
Hi

Yeah great remarks
- descent : you may more precisely check the individual values of ascent & descent. I'll do some tests on my own too, but a font with a size of X does not mean its line height is X. I think it is more the capHeight for example. The ascent, due to glyphs that goes a bit higher, may be more than the point size. I will have to check that.
- textFrame : I think I did recreate a new one each time in `drawRect` because the text is often redrawn if the bounds of the label changes, or the attributedText itself changes or anything that can affect the layout so we need to recompute the textFrame. But you're right, if we think of every use cases, we can effectively optimize `drawRect` by avoiding recomputing the textFrame if not NULL, and only release and setting this textFrame to NULL (thus forcing to recompute on the next call to `drawRect`) if the bounds or the attributedText itself changed. Good idea.
- `centerVertically` / `extendBottomToFit`: exact, we **must** consider these cases when detecting links, or else a text that is centered vertically will use the "uncentered" version for detecting links, and this is wrong. Nice catch.

**Comment by AliSoftware** [comment]
Great for solving the mysteries :D

Maybe it would be a better idea that I ignore this pull request and instead you send me another pull requests with your corrections/fixes on descent/CGRectIntegral/... ? (before we start to work on the optimization of not creating the textFrame eact time and on the fix on centerVertically in link detection ?)

(Really have to find some time for this merge before the fork goes too far :P)

**Comment by stigi** [comment]
Let's do this step by step:
- I'll close this pull request and create a new one which includes the changes we spoke about in a separate commit
- create a new issue for `centerVertically`/`extendBottomToFit:` we should tackle this after issue #10
- also create an issue for having a cached textFrame that get's invalidated on change of frame and attributedText. This should speed things up.

After that I think we should just use it and create issues as they appear. But those things should be done so you, me and everyone else have a solid foundation to work with.

**Pull request closed without merging**
