### PR TITLE
arc support

### PR DESCRIPTION
**Pull request by greenisus**
this may be a bit premature, but i wanted to use OHAttributedLabel in a new project, so i converted it and the example project to use ARC and it seems to be working nicely.

### CODE REVIEW

**Comment by AliSoftware** [comment]
Great! I won't have much time this week to check your code and merge this right now, but I will definitely give it a look and merge it ASAP, thanks !

**Comment by greenisus** [comment]
No worries!  I'm already using it; just figured I'd contribute it back in case you were interested :)

Mike
@greenisus

**Comment by a2** [comment]
@Greensius Your work looks solid. How long until we can expect this to be accepted?

**Comment by greenisus** [comment]
thanks!  i have no idea :)  if you want it now you can just use my fork i guess

**Comment by AliSoftware** [comment]
Hi

Sorry won't have much time to merge this soon.

The code seems ok for ARC, the problem is that I can't merge it right away as this will break the compatibility with non-ARC code.

To merge this properly, I'll have to make the code both valid for ARC and non-ARC projects to be sure that it is still compatible for everyone, as this is the "master" branch of the repo so it is important to keep the compatibility for everyone (I can't force everyone to use ARC, I still have projects without ARC myself)

So before doing this merge we will have to use `#if` and other `#define` directives to make this cross compatible.

**Comment by a2** [comment]
I could do that and submit a pull request later today.

**Comment by AliSoftware** [comment]
Great, thanks @pandamonia :)

I don't have my mac available for a couple of weeks but will look at it then. Thx!

**Comment by a2** [comment]
Just went through and added preprocessor macros to conditionally support ARC. See my [pull request](https://github.com/AliSoftware/OHAttributedLabel/pull/48).

**Comment by AliSoftware** [comment]
Cool, great work !
have a lot of emergencies on other projects right now but will definitely merge this soon (probably this weekend)

Thanks a lot :)

**Comment by a2** [comment]
In retrospect, you may want to create a separate ARC branch instead of the conditional directives I wrote. When making changes in the future, you won't want to remember to add these breaks in there. Most other projects have separate ARC branches, so I think that's a better idea for the future.

That being said, I won't close the pull request until you decide either way.

**Comment by AliSoftware** [comment]
Actually I intend to encapsulate the class into a framework (as I did for my other `OHGridView` class/repo recently) so that the build settings of `OHAttributedLabel` won't mix will the build settings of the user's project.

This way I will be able to keep OHAttributedLabel with manual memory mgmt as always, build it without ARC, but still make the framework usable in a project using ARC.
Will keep you posted once this is done.

**Comment by greenisus** [comment]
Good idea.  I've started taking that approach as well.

**Comment by stefanklumpp** [comment]
Any updates on this?

**Comment by mRs-** [comment]
would be nice to get a update here :)

**Pull request closed without merging**
